INSERT INTO track (name,location,twitter_handle)
    VALUES ('Atlanta Motor Speedway','Hampton, Georgia',''),
        ('Auto Club Speedway','Fontana, California',''),
        ('Baltimore','Baltimore, Maryland',''),
        ('Barber Motorsports Park','Birmingham, Alabama',''),
        ('Charlotte Motor Speedway','Concord, North Carolina',''),
        ('Chicagoland Speedway','Joliet, Illinois',''),
        ('Detroit Belle Isle','Detroit, Michigan',''),
        ('Dover Downs International Speedway','Dover, Delaware',''),
        ('Edmonton City Centre (Blatchford Field) Airport','Edmonton, Alberta, Canada',''),
        ('Gateway Motorsports Park','Madison, Illinois',''),
        ('Homestead-Miami Speedway','Homestead, Florida',''),
        ('MDAnderson Cancer Center Speedway at NRG Park','Houston, Texas',''),
        ('Indianapolis Motor Speedway','Speedway, Indiana',''),
        ('Iowa Speedway','Newton, Iowa',''),
        ('Kansas Speedway','Kansas City, Kansas',''),
        ('Kentucky Speedway','Sparta, Kentucky',''),
        ('Las Vegas Motor Speedway','Sunrise Manor, Nevada',''),
        ('Long Beach','Long Beach, California',''),
        ('Michigan International Speedway','Brooklyn, Michigan',''),
        ('Mid-Ohio Sports Car Course','Lexington, Ohio',''),
        ('Milwaukee Mile','West Allis, Wisconsin',''),
        ('Twin Ring Motegi','Motegi, Tochigi, Japan',''),
        ('Nashville Superspeedway','Lebanon, Tennessee',''),
        ('Nazareth Speedway','Nazareth, Pennsylvania',''),
        ('New Hampshire Motor Speedway','Loudon, New Hampshire',''),
        ('NOLA Motorsports Park','Avondale, Louisiana',''),
        ('Phoenix International Raceway','Avondale, Arizona',''),
        ('Pikes Peak International Raceway','Fountain, Colorado',''),
        ('Pocono Raceway','Long Pond, Pennsylvania',''),
        ('Richmond International Raceway','Richmond, Virginia',''),
        ('Road America','Elkhart Lake, Wisconsin',''),
        ('St. Petersburg','St. Petersburg, Florida',''),
        ('Sao Paulo','Sao Paulo, Sao Paulo, Brazil',''),
        ('Sonoma Raceway','Sonoma, California',''),
        ('Surfers Paradise','Surfers Paradise, Queensland, Australia',''),
        ('Texas Motor Speedway','Fort Worth, Texas',''),
        ('Exhibition Place','Toronto, Ontario, Canada',''),
        ('Walt Disney World Speedway','Bay Lake, Florida',''),
        ('Watkins Glen International','Watkins Glen, New York','');